### ISSUE TITLE
Ownership of library

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/purescript-sammy#2]
As with purescript-contrib/purescript-handlebars#2, would you mind taking this one back too?

Thanks!

**Comment by paf31** [comment]
@wfaler Any thoughts on maintaining this?

**Comment by wfaler** [comment]
Forked it back.

**Comment by garyb** [comment]
@wfaler could you move this and `purescript-handlebars` back rather than fork it back? That way it will still work for people installing via bower. Thanks! (You should have permission to do so).

**Comment by paf31** [comment]
I've updated this for 0.7, and I'm happy to take over maintainership if need be. After spending a bit of time with it today, Sammy is quite nice :)
